services:
  configserver:
    image: "ldeepak/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"

    # Define a healthcheck to ensure the configserver is up and running before other services depend on it
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      # check every 10 seconds, wait 5 seconds before timing out, retry up to 10 times, and allow a start period of 10 seconds
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eurekaserver:
    image: "ldeepak/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"

    # Define a healthcheck to ensure the eurekaserver is up and running before other services depend on it
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      # check every 10 seconds, wait 5 seconds before timing out, retry up to 10 times, and allow a start period of 10 seconds
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "ldeepak/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  loans:
    image: "ldeepak/loans:s8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  cards:
    image: "ldeepak/cards:s8"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: "bridge"