# This file contains common configuration for microservices to be used in different deployment scenarios.
services:
  network-deploy-service:
    networks:
      - eazybank

  # This is the base configuration for microservices that will be used in different deployment scenarios.
  # It extends the network-deploy-service to ensure that all microservices are part of the same network and can communicate with each other.
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  # This configuration extends the microservice-base-config and adds specific environment variables for connecting to the Config Server
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    # This makes sure that the service starts only when configserver is healthy. This is important because microservices will try to connect to the configserver at the startup to get the configurations, so configserver should be up and running before microservices start.
    depends_on:
      configserver:
        condition: service_healthy
    # Setting these properties via environment variables. It follows the syntax of uppercase with underscores, instead of dots.
    # For example, SPRING_PROFILES_ACTIVE corresponds to spring.profiles.active in application.yaml. This value in environment variable will override the one in application.yaml.
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" # passing as environment variable because for local development the config server url would be localhost but in docker environment should use the service name configserver

  # This configuration extends the microservice-base-config and adds specific environment variables for connecting to the Eureka Server
  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    # This makes sure that the service starts only when eurekaserver is healthy. This is important because microservices will try to connect to the eurekaserver at the startup to register themselves, so eurekaserver should be up and running before microservices start.
    depends_on:
      eurekaserver:
        condition: service_healthy
    # Setting these properties via environment variables. It follows the syntax of uppercase with underscores, instead of dots.
    # For example, SPRING_PROFILES_ACTIVE corresponds to spring.profiles.active in application.yaml. This value in environment variable will override the one in application.yaml.
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/" # passing as environment variable because for local development the eureka server url would be localhost but in docker environment should use the service name eurekaserver